In [1]:
import pandas as pd
import numpy as np
import pickle
import patsy

In [2]:
pd.set_option('display.max_colwidth', -1)

In [3]:
df = pd.read_csv('loan.csv')

/home/brendanfitzpatrick/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df_key = pd.read_excel('LCDataDictionary.xlsx')
df_key.set_index('LoanStatNew')

                                                                                                                                                                                                                                   Description
LoanStatNew
addr_state                  The state provided by the borrower in the loan application
annual_inc                  The self-reported annual income provided by the borrower during registration.
annual_inc_joint            The combined self-reported annual income provided by the co-borrowers during registration
application_type            Indicates whether the loan is an individual application or a joint application with two co-borrowers
collection_recovery_fee     post charge off collection fee
collections_12_mths_ex_med  Number of collections in 12 months excluding medical collections
delinq_2yrs                 The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
desc                        Loan description provided by the borrower
dti                         A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.
dti_joint                   A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income
earliest_cr_line            The month the borrower's earliest reported credit line was opened
emp_length                  Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
emp_title                   The job title supplied by the Borrower when applying for the loan.*
fico_range_high             The upper boundary range the borrower’s FICO at loan origination belongs to.
fico_range_low              The lower boundary range the borrower’s FICO at loan origination belongs to.
funded_amnt                 The total amount committed to that loan at that point in time.
funded_amnt_inv             The total amount committed by investors for that loan at that point in time.
grade                       LC assigned loan grade
home_ownership              The home ownership status provided by the borrower during registration. Our values are: RENT, OWN, MORTGAGE, OTHER.
id                          A unique LC assigned ID for the loan listing.
initial_list_status         The initial listing status of the loan. Possible values are – W, F
inq_last_6mths              The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
installment                 The monthly payment owed by the borrower if the loan originates.
int_rate                    Interest Rate on the loan
is_inc_v                    Indicates if income was verified by LC, not verified, or if the income source was verified
issue_d                     The month which the loan was funded
last_credit_pull_d          The most recent month LC pulled credit for this loan
last_fico_range_high        The upper boundary range the borrower’s last FICO pulled belongs to.
last_fico_range_low         The lower boundary range the borrower’s last FICO pulled belongs to.
last_pymnt_amnt             Last total payment amount received
...                                                                                          ...
title                       The loan title provided by the borrower
total_acc                   The total number of credit lines currently in the borrower's credit file
total_pymnt                 Payments received to date for total amount funded
total_pymnt_inv             Payments received to date for portion of total amount funded by investors
total_rec_int               Interest received to date
total_rec_late_fee          Late fees received to date
total_rec_prncp             Principal received to date
url                         URL for the LC page with listing data.
verified_status_joint       Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified
zip_code                    The first 3 numbers of the zip code provided by the borrower in the loan application.
open_acc_6m                 Number of open trades in last 6 months
open_il_6m                  Number of currently active installment trades
open_il_12m                 Number of installment accounts opened in past 12 months
open_il_24m                 Number of installment accounts opened in past 24 months
mths_since_rcnt_il          Months since most recent installment accounts opened
total_bal_il                Total current balance of all installment accounts
il_util                     Ratio of total current balance to high credit/credit limit on all install acct
open_rv_12m                 Number of revolving trades opened in past 12 months
open_rv_24m                 Number of revolving trades opened in past 24 months
max_bal_bc                  Maximum current balance owed on all revolving accounts
all_util                    Balance to credit limit on all trades
total_rev_hi_lim            Total revolving high credit/credit limit
inq_fi                      Number of personal finance inquiries
total_cu_tl                 Number of finance trades
inq_last_12m                Number of credit inquiries in past 12 months
acc_now_delinq              The number of accounts on which the borrower is now delinquent.
tot_coll_amt                Total collection amounts ever owed
tot_cur_bal                 Total current balance of all accounts
NaN                         NaN
NaN                         * Employer Title replaces Employer Name for all loans listed after 9/23/2013

[80 rows x 1 columns]

&nbsp;
### Remove sub policy and current loans
&nbsp;

In [5]:
df = df[(df.loan_status == 'Fully Paid')
                | (df.loan_status == 'Charged Off')
                | (df.loan_status == 'Default')]

&nbsp;
### Combine 'Charged Off' and 'Default'
&nbsp;

In [6]:
df['loan_status'] = df.loan_status.apply(lambda x: 'Fully Paid' 
                                              if x == 'Fully Paid' 
                                              else 'Default')

In [7]:
df.loan_status.unique()

array(['Fully Paid', 'Default'], dtype=object)

&nbsp;
### Separate Lending Club's Allocation
&nbsp;

In [8]:
df['lc_allocation'] = df.loan_amnt - df.funded_amnt_inv

In [9]:
df['term'] = pd.to_numeric(df.term.str.strip().str.replace('months',''))

&nbsp;
### Remove NaN's
&nbsp;

In [10]:
df = df[df.revol_util.notnull()]

&nbsp;
### Create Dummy Variables
&nbsp;

In [11]:
def yes_no_binary(x):
    if (x=='y'):
        return 1
    if (x=='n'):
        return 0

In [12]:
df['pymnt_plan'] = df['pymnt_plan'].apply(yes_no_binary)

In [13]:
def whole_fractional_binary(x):
    if (x=='w'):
        return 1
    if (x=='f'):
        return 0

In [14]:
df['initial_list_status'] = df['initial_list_status'].apply(whole_fractional_binary)

In [15]:
def event_last_year(x):
    if (x < 12*1):
        return 1
    else:
        return 0

In [16]:
def event_last_two_years(x):
    if (x < 12*2):
        return 1
    else:
        return 0

In [17]:
def event_last_five_years(x):
    if (x < 12*5):
        return 1
    else:
        return 0

In [18]:
df['major_derog_within_1'] = df.mths_since_last_major_derog.apply(event_last_year)
df['major_derog_within_2'] = df.mths_since_last_major_derog.apply(event_last_two_years)
df['major_derog_within_5'] = df.mths_since_last_major_derog.apply(event_last_five_years)

In [19]:
df['record_within_1'] = df.mths_since_last_record.apply(event_last_year)
df['record_within_2'] = df.mths_since_last_record.apply(event_last_two_years)
df['record_within_5'] = df.mths_since_last_record.apply(event_last_five_years)

In [20]:
df['emp_length'].unique()

array(['10+ years', '< 1 year', '3 years', '9 years', '4 years', '5 years',
       '1 year', '6 years', '2 years', '7 years', '8 years', 'n/a'], dtype=object)

In [21]:
def emp_length_10_map(x):
    if(x == '10+ years'):
        return 1
    else:
        return 0

In [22]:
def emp_length_5_map(x):
    if(x == '10+ years' or x == '9 years' or x == '8 years' 
       or x == '7 years' or x == '6 years' or x == '5 years'):
        return 1
    else:
        return 0

In [23]:
def emp_length_1_map(x):
    if(x == '< 1 year' or x == 'n/a'):
        return 0
    else:
        return 1

In [24]:
df['emp_length_greater_1_yr'] = df.emp_length.apply(emp_length_1_map)
df['emp_length_greater_5_yrs'] = df.emp_length.apply(emp_length_5_map)
df['emp_length_greater_10_yrs'] = df.emp_length.apply(emp_length_10_map)

In [25]:
df['earliest_cr_line'] = pd.to_datetime(df.earliest_cr_line,format='%b-%Y')
df['issue_d'] = pd.to_datetime(df.issue_d,format='%b-%Y')

In [26]:
df['earliest_cr_line_delta'] = (df.issue_d - df.earliest_cr_line) / np.timedelta64(1, 'M')

In [27]:
grades_df = patsy.dmatrix('grade',data=df,return_type='dataframe')
grades_columns = ['grade_intercept',
                  'B_grade',
                  'C_grade',
                  'D_grade',
                  'E_grade',
                  'F_grade',
                  'G_grade']
grades_df.columns = grades_columns

In [28]:
df = df.join(grades_df)

In [29]:
home_ownership_df = patsy.dmatrix('home_ownership',data=df,return_type='dataframe')
home_ownership_columns = ['home_ownership_intercept',
                          'home_ownership_mortgage',
                          'home_ownership_none',
                          'home_ownership_other',
                          'home_ownership_own',
                          'home_ownership_rent']
home_ownership_df.columns = home_ownership_columns

In [30]:
df = df.join(home_ownership_df)

In [31]:
verification_df = patsy.dmatrix('verification_status',data=df,return_type='dataframe')
verification_columns = ['verification_intercept',
                        'source_verified',
                        'verified']
verification_df.columns = verification_columns

In [32]:
df = df.join(verification_df)

In [33]:
"""emp_length_df = patsy.dmatrix('emp_length',data=df,return_type='dataframe')
emp_length_columns = ['emp_length_intercept', 
                      'emp_length_greater_10_yrs',
                      'emp_length_2_yrs',
                      'emp_length_3_yrs',
                      'emp_length_4_yrs',
                      'emp_length_5_yrs',
                      'emp_length_6_yrs',
                      'emp_length_7_yrs',
                      'emp_length_8_yrs',
                      'emp_length_9_yrs', 
                      'emp_length_less_1_yr',
                      'emp_length_n/a]']
emp_length_df.columns = emp_length_columns"""

"emp_length_df = patsy.dmatrix('emp_length',data=df,return_type='dataframe')\nemp_length_columns = ['emp_length_intercept', \n                      'emp_length_greater_10_yrs',\n                      'emp_length_2_yrs',\n                      'emp_length_3_yrs',\n                      'emp_length_4_yrs',\n                      'emp_length_5_yrs',\n                      'emp_length_6_yrs',\n                      'emp_length_7_yrs',\n                      'emp_length_8_yrs',\n                      'emp_length_9_yrs', \n                      'emp_length_less_1_yr',\n                      'emp_length_n/a]']\nemp_length_df.columns = emp_length_columns"

In [34]:
"""df = df.join(emp_length_df)"""

'df = df.join(emp_length_df)'

BF NOTE: Try outstanding principal LC allocation if in need of additional features

&nbsp;
### Remove columns with high NaNs
&nbsp;

In [35]:
df = df.drop(['open_acc_6m',
              'open_il_6m',
              'open_il_12m',
              'open_il_24m',
              'mths_since_rcnt_il',
              'total_bal_il',
              'il_util',
              'open_rv_12m',
              'open_rv_24m',
              'max_bal_bc',
              'all_util',
              'inq_fi',
              'total_cu_tl',
              'inq_last_12m'], 1)

### Group seperate DataFrames

&nbsp;

Create three seperate dataframes for:
  * Individual loans
  * Joint loans
  [* Loans that do not meet Lending Club's credit policy]
  
&nbsp;

In [36]:
"""df_sub_policy = df[(df.loan_status == 'Does not meet the credit policy. Status:Fully Paid') 
                   | (df.loan_status == 'Does not meet the credit policy. Status:Charged Off')]"""

"df_sub_policy = df[(df.loan_status == 'Does not meet the credit policy. Status:Fully Paid') \n                   | (df.loan_status == 'Does not meet the credit policy. Status:Charged Off')]"

&nbsp;
### Remove sub-policy loans
&nbsp;

In [37]:
df = df[(df.loan_status != 'Does not meet the credit policy. Status:Fully Paid') & (df.loan_status != 'Does not meet the credit policy. Status:Charged Off')]

In [38]:
df_joint = df[df.application_type=='JOINT']

In [39]:
df_inv = df[df.application_type=='INDIVIDUAL']

In [40]:
df.application_type.unique()

array(['INDIVIDUAL', 'JOINT'], dtype=object)

In [41]:
df_inv.drop('annual_inc_joint',1)
df_inv.drop('dti_joint',1)
df_inv.drop('verification_status_joint',1)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,G_grade,home_ownership_intercept,home_ownership_mortgage,home_ownership_none,home_ownership_other,home_ownership_own,home_ownership_rent,verification_intercept,source_verified,verified
0,1077501,1296599,5000.0,5000.0,4975.000000,36,10.65,162.87,B,B2,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1077430,1314167,2500.0,2500.0,2500.000000,60,15.27,59.83,C,C4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,1077175,1313524,2400.0,2400.0,2400.000000,36,15.96,84.33,C,C5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,1076863,1277178,10000.0,10000.0,10000.000000,36,13.49,339.31,C,C1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
5,1075269,1311441,5000.0,5000.0,5000.000000,36,7.90,156.46,A,A4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
7,1072053,1288686,3000.0,3000.0,3000.000000,36,18.64,109.43,E,E1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
8,1071795,1306957,5600.0,5600.0,5600.000000,60,21.28,152.39,F,F2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
9,1071570,1306721,5375.0,5375.0,5350.000000,60,12.69,121.45,B,B5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
10,1070078,1305201,6500.0,6500.0,6500.000000,60,14.65,153.45,C,C3,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
11,1069908,1305008,12000.0,12000.0,12000.000000,36,12.69,402.54,B,B5,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
12,1064687,1298717,9000.0,9000.0,9000.000000,36,13.49,305.38,C,C1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
13,1069866,1304956,3000.0,3000.0,3000.000000,36,9.91,96.68,B,B1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
14,1069057,1303503,10000.0,10000.0,10000.000000,36,10.65,325.74,B,B2,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
15,1069759,1304871,1000.0,1000.0,1000.000000,36,16.29,35.31,D,D1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
16,1065775,1299699,10000.0,10000.0,10000.000000,36,15.27,347.98,C,C4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
17,1069971,1304884,3600.0,3600.0,3600.000000,36,6.03,109.57,A,A1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,1062474,1294539,6000.0,6000.0,6000.000000,36,11.71,198.46,B,B3,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
19,1069742,1304855,9200.0,9200.0,9200.000000,36,6.03,280.01,A,A1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
20,1069740,1284848,20250.0,20250.0,19142.161077,60,15.27,484.63,C,C4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
21,1039153,1269083,21000.0,21000.0,21000.000000,36,12.42,701.73,B,B4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
22,1069710,1304821,10000.0,10000.0,10000.000000,36,11.71,330.76,B,B3,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
23,1069700,1304810,10000.0,10000.0,10000.000000,36,11.71,330.76,B,B3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
24,1069559,1304634,6000.0,6000.0,6000.000000,36,11.71,198.46,B,B3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
25,1069697,1273773,15000.0,15000.0,15000.000000,36,9.91,483.38,B,B1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
26,1069800,1304679,15000.0,15000.0,8725.000000,36,14.27,514.64,C,C2,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
27,1069657,1304764,5000.0,5000.0,5000.000000,60,16.77,123.65,D,D2,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
28,1069799,1304678,4000.0,4000.0,4000.000000,36,11.71,132.31,B,B3,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29,1047704,1278806,8500.0,8500.0,8500.000000,36,11.71,281.15,B,B3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
30,1032111,1261745,4375.0,4375.0,4375.000000,36,7.51,136.11,A,A3,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
31,1069539,1304608,31825.0,31825.0,31825.000000,36,7.90,995.82,A,A4,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887164,37620521,40383278,24000.0,24000.0,24000.000000,36,6.49,735.47,A,A2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887177,37670482,40433236,24875.0,24875.0,24875.000000,60,25.83,742.27,G,G2,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
887178,37810537,40573279,26500.0,26500.0,26500.000000,36,23.99,1039.54,F,F2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887185,37197690,39970466,24000.0,24000.0,24000.000000,60,15.99,583.51,D,D2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887187,37700380,40473130,15000.0,15000.0,14975.000000,60,12.39,336.64,C,C1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
887189,37650375,40413110,20000.0,20000.0,20000.000000,36,14.99,693.21,C,C5,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
887193,37640409,40403154,11200.0,11200.0,11200.000000,60,19.99,296.67,E,E3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
887194,37650403,40413143,20000.0,20000.0,20000.000000,36,14.31,686.57,C,C4,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
887198,37790415,40553149,30000.0,30000.0,30000.000000,36,14.99,1039.82,C,C5,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887202,36118265,38829794,12000.0,12000.0,12000.000000,36,11.99,398.52,B,B5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
887215,36400285,39031612,12825.0,12825.0,12825.000000,36,17.14,458.15,D,D4,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
887249,37357154,40119871,27650.0,27650.0,27650.000000,60,21.99,763.51,E,E5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
887254,37068125,39536839,7200.0,7200.0,7200.000000,36,14.99,249.56,C,C5,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
887263,37317965,40080791,25000.0,25000.0,25000.000000,60,12.39,561.06,C,C1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887264,36801355,39554067,20000.0,20000.0,20000.000000,36,12.99,673.79,C,C2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887268,37297854,40040662,20000.0,20000.0,20000.000000,36,14.99,693.21,C,C5,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887275,37247819,40020610,29675.0,29675.0,29675.000000,60,13.66,685.27,C,C3,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
887279,37127712,39900482,5875.0,5875.0,5875.000000,36,16.49,207.98,D,D3,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
887290,37167534,39940303,35000.0,35000.0,35000.000000,60,24.99,1027.10,F,F4,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887303,37087435,39850186,12000.0,12000.0,12000.000000,36,17.86,432.99,D,D5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
887308,37227443,40000189,2725.0,2725.0,2725.000000,36,17.86,98.33,D,D5,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887330,37077186,39839905,14000.0,14000.0,14000.000000,36,15.99,492.13,D,D2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887332,37187152,39959868,15000.0,15000.0,15000.000000,36,12.39,501.02,C,C1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887346,36808246,39560970,6000.0,6000.0,6000.000000,36,10.49,194.99,B,B3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
887347,37041208,39803931,17000.0,17000.0,17000.000000,60,15.99,413.32,D,D2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
887351,36743377,39486112,4200.0,4200.0,4200.000000,36,15.99,147.64,D,D2,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887364,36231718,38943165,10775.0,10775.0,10775.000000,36,6.03,327.95,A,A1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
887366,36241316,38952731,6225.0,6225.0,6225.000000,36,16.49,220.37,D,D3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
887369,36421485,39142898,4000.0,4000.0,4000.000000,36,8.67,126.59,B,B1,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
887371,36260758,38972123,10850.0,10850.0,10850.000000,36,19.24,399.04,E,E2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [42]:
with open('df_inv.pkl', 'wb') as picklefile:
    pickle.dump(df_inv, picklefile)

In [43]:
with open('df_joint.pkl', 'wb') as picklefile:
    pickle.dump(df_joint, picklefile)

In [49]:
df_both = df[(df.application_type=='JOINT') | (df.application_type=='INDIVIDUAL')]

In [50]:
with open('df_both.pkl', 'wb') as picklefile:
    pickle.dump(df_both, picklefile)

In [44]:
"""with open('df_sub_policy.pkl', 'wb') as picklefile:
    pickle.dump(df_sub_policy, picklefile)"""

"with open('df_sub_policy.pkl', 'wb') as picklefile:\n    pickle.dump(df_sub_policy, picklefile)"

In [45]:
!ls -l

total 963380
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick     22092 Aug  2 09:37 03-mcnulty_brendan_choropleths.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick     43418 Aug  2 09:52 03_mcnulty_brendan_cleaning.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick      8890 Aug  2 09:50 03-mcnulty_brendan_donuts.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick      6552 Aug  1 22:00 03-mcnulty_brendan_flask_model.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick     78461 Jul 30 03:41 03_mcnulty_brendan_modeling-Copy1.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick     68462 Aug  1 22:31 03_mcnulty_brendan_modeling.ipynb
-rwxr-xr-x 1 brendanfitzpatrick brendanfitzpatrick    172221 Jul 28 21:30 challenge_set_1_brendan.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick    178337 Jul 28 15:12 challenge_set_7_brendan.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick     28379 Jul 28 20:40 challenge_set_8_brendan.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick       686 Aug  2 09:20 defaults_by_state.csv
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick 216245852 Aug  2 09:52 df_inv.pkl
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick      4842 Aug  2 09:52 df_joint.pkl
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick         0 Jul 30 17:31 df_sub_policy.pkl
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick  99995025 Aug  1 21:03 features.pkl
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick   1737231 Jul 29 15:52 Intro_to_Regression_Solutions.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick     20995 Jul 27 21:25 LCDataDictionary.xlsx
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick     11942 Jul 29 16:27 Lending_Club_Domain_Knowledge.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick    355500 Jul 28 20:55 Linear_Assumptions_testing.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick 441771600 Jul 30 17:05 loan.csv
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick       743 Aug  2 08:56 loans_by_state.csv
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick      1371 Jul 28 13:39 pair.html
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick     29551 Jul 31 20:00 Poisson_GLM.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick       887 Aug  2 08:49 state_counts.csv
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick      2139 Aug  1 21:58 state_counts.pkl
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick     60044 Jul 28 13:17 SVM_digits.ipynb
-rw-r--r-- 1 brendanfitzpatrick brendanfitzpatrick    315927 Jul 28 13:17 SVMs.ipynb
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick   6977007 Aug  1 21:03 target.pkl
-rw-rw-r-- 1 brendanfitzpatrick brendanfitzpatrick 218293851 Aug  1 22:30 ui_data.pkl